name: wine_quality_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - scikit-learn>=1.5
  - pandas>=2.0
  - numpy>=1.26
  - matplotlib>=3.8
  - seaborn>=0.13
  - pip:
    - mlflow>=3.0
    - click>=8.0
    - joblib
